FROM gcc:15.2.0

# Install LLVM 20
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        lsb-release wget && \
    wget https://apt.llvm.org/llvm.sh && \
    chmod +x ./llvm.sh && ./llvm.sh 20 all && rm llvm.sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
