name: 'Setup vcpkg with cache'
description: 'Sets up vcpkg with binary caching'

inputs:
  os:
    description: 'Operating system identifier for cache key (e.g., ubuntu-22.04, macos-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_BINARY_SOURCES: default,readwrite

    - name: Set up binary cache
      uses: actions/cache@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        # Invalidate cache when vcpkg manifests or overlay ports change
        key: ${{ inputs.os }}-${{ runner.arch }}-vcpkg-binary-cache-${{ hashFiles('vcpkg*.json', 'ports-overlays/**') }}
        restore-keys: |
          ${{ inputs.os }}-${{ runner.arch }}-vcpkg-binary-cache-
          ${{ runner.os }}-${{ runner.arch }}-vcpkg-binary-cache-
